<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User extends CI_Model
{

    public $table = 'pengguna';
    public $id = 'id_pengguna';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

   
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    
    //login
    function cek_login($table,$where){
        return $this->db->get_where($table,$where);
    }
}

/* End of file Admin_Admin_Model.php */
/* Location: ./application/models/Admin_Admin_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-11 08:36:41 */
/* http://harviacode.com */
