<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Berita_admin extends CI_Model
{

    public $table = 'berita';
	public $table2 = 'panti_asuhan';
    //public $id = 'id_agenda';
	//public $ida = 'id_host';
	//public $idu = 'id_user';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

   
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
	
    
    //read data
	
	function get_data_all($number,$offset){
		$this->db->select('a.id_berita,a.judul_berita,a.tanggal_berita,a.foto_berita,a.isi_berita,p.nama_panti_asuhan');
		$this->db->from('berita a');
		$this->db->join('panti_asuhan p','a.id_panti_asuhan=p.id_panti_asuhan');
        $query = $this->db->get('',$number,$offset);
        return $query->result();
    }
	function jumlah_data(){
        return $this->db->get('berita')->num_rows();
    }
	
	
	public function getIdBerita()
	  {
		$this->db->select_max('id_berita');
		$this->db->from('berita');
		$data=$this->db->get('')->row();
		return $data->id_donatur;
	  }	
  
	function hapus($id_berita)
		{
			$this->db->where('id_berita', $id_berita);
			$this->db->delete('berita');
		}
	
	function getData_By_Id($id_berita)
	{
		$this->db->select('*');
		$this->db->from('berita');
		$this->db->where('id_berita',$id_berita);
		$data= $this->db->get('')->row();
		return $data;
	}
	
	function updateBerita($data)
	{
		$this->db->where('id_berita', $data['id_berita']);
		$this->db->update('berita',$data);
	}
	
	public function get_by_id($id_berita)
	{
		$this->db->from($this->table);
		$this->db->where('id_berita',$id_berita);
		$query = $this->db->get();

		return $query->row();
	}
	
	public function get_by_id_view($id_berita)
	{
		$this->db->select('a.id_berita,a.judul_berita,a.tanggal_berita,a.foto_berita,a.isi_berita,p.nama_panti_asuhan');
		$this->db->from('berita a');
		$this->db->join('panti_asuhan p','a.id_berita=p.id_panti_asuhan');
		$this->db->where('a.id_berita',$id_berita);
		$query = $this->db->get();

		return $query->row();
	}
	
	public function cari($cari)
	{
		$cek=true;
		$this->db->select('a.id_berita,a.judul_berita,a.tanggal_berita,a.foto_berita,a.isi_berita,p.nama_panti_asuhan');
		$this->db->from('berita a');
		$this->db->join('panti_asuhan p','a.id_panti_asuhan=p.id_panti_asuhan');
		$this->db->like("a.judul_berita",$cari);
        $this->db->or_like("a.tanggal_berita",$cari);
		$num_rows=$this->db->count_all_results('');
		if($num_rows==0)
		{
		  $cek=false;
		}
		return $cek;
	}
	
	public function hasilcari($cari)
	{
		$this->db->select('a.id_berita,a.judul_berita,a.tanggal_berita,a.foto_berita,a.isi_berita,p.nama_panti_asuhan');
		$this->db->from('berita a');
		$this->db->join('panti_asuhan p','a.id_panti_asuhan=p.id_panti_asuhan');
		$this->db->like("a.judul_berita",$cari);
        $this->db->or_like("a.tanggal_berita",$cari);
		
		$query = $this->db->get('');

		return $query->result();
	}
}

/* End of file Admin_Admin_Model.php */
/* Location: ./application/models/Admin_Admin_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-11 08:36:41 */
/* http://harviacode.com */
