<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Donatur_admin extends CI_Model
{

    public $table = 'donatur';
	public $table2 = 'pengguna';
    //public $id = 'id_agenda';
	//public $ida = 'id_host';
	//public $idu = 'id_user';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

   
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
	
    
    //read data
	
	function get_data_all($number,$offset){
		$this->db->select('a.id_donatur,a.nama_donatur,b.email,a.telp_donatur,a.alamat_donatur,a.foto_donatur');
		$this->db->from('donatur a');
        $this->db->join('pengguna b','a.id_donatur=b.id_donatur');
		$query = $this->db->get('',$number,$offset);
        return $query->result();
    }
	
	function jumlah_data(){
        return $this->db->get('donatur')->num_rows();
    }
	
	public function getIdDonatur()
  {
    $this->db->select_max('id_donatur');
    $this->db->from('donatur');
    $data=$this->db->get('')->row();
    return $data->id_donatur;
  }
  
  function hapus($id_donatur)
	{
		$this->db->where('id_donatur', $id_donatur);
		$this->db->delete('donatur');
	}

	function hapuspengguna($id_donatur)
	{
		$this->db->where('id_donatur', $id_donatur);
		$this->db->delete('pengguna');
	}
	
	function getData_By_Id($id_donatur)
	{
		$this->db->select('*');
		$this->db->from('donatur');
		$this->db->where('id_donatur',$id_donatur);
		$data= $this->db->get('')->row();
		return $data;
	}
	
	function updateDonatur($DataDonatur)
	{
		$this->db->where('id_donatur', $DataDonatur['id_donatur']);
		$this->db->update('donatur',$DataDonatur);
	}
	
	public function get_by_id($id_donatur)
	{
		$this->db->from($this->table);
		$this->db->where('id_donatur',$id_donatur);
		$query = $this->db->get();

		return $query->row();
	}
	
	public function cari($cari)
	{
		$cek=true;
		$this->db->select('a.id_donatur,a.nama_donatur,b.email,a.telp_donatur,a.alamat_donatur,a.foto_donatur');
		$this->db->from('donatur a');
        $this->db->join('pengguna b','a.id_donatur=b.id_donatur');
		$this->db->like("a.nama_donatur",$cari);
        $this->db->or_like("b.email",$cari);
		$this->db->or_like("a.telp_donatur",$cari);
		$num_rows=$this->db->count_all_results('');
		if($num_rows==0)
		{
		  $cek=false;
		}
		return $cek;
	}
	
	public function hasilcari($cari)
	{
		$this->db->select('a.id_donatur,a.nama_donatur,b.email,a.telp_donatur,a.alamat_donatur,a.foto_donatur');
		$this->db->from('donatur a');
        $this->db->join('pengguna b','a.id_donatur=b.id_donatur');
		$this->db->like("a.nama_donatur",$cari);
        $this->db->or_like("b.email",$cari);
		$this->db->or_like("a.telp_donatur",$cari);
		$query = $this->db->get('');

		return $query->result();
	}
}

/* End of file Admin_Admin_Model.php */
/* Location: ./application/models/Admin_Admin_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-11 08:36:41 */
/* http://harviacode.com */
