<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kegiatan_admin extends CI_Model
{

    public $table = 'kegiatan';
	public $table2 = 'panti_asuhan';
	public $table3 = 'donatur';
    //public $id = 'id_agenda';
	//public $ida = 'id_host';
	//public $idu = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //read data
	
	function get_data_all($number,$offset){
		$this->db->select('a.id_kegiatan,b.nama_donatur,c.nama_panti_asuhan,a.nama_kegiatan,a.tanggal_kegiatan,a.jam_kegiatan,a.deskripsi_kegiatan,a.status_kegiatan');
		$this->db->from('kegiatan a');
		$this->db->join('donatur b','a.id_donatur=b.id_donatur');
		$this->db->join('panti_asuhan c','a.id_panti_asuhan=c.id_panti_asuhan');
        $query = $this->db->get('',$number,$offset);
        return $query->result();
    }
	function jumlah_data(){
        return $this->db->get('kegiatan')->num_rows();
    }
	
	function hapus($id_kegiatan)
	{
		$this->db->where('id_kegiatan', $id_kegiatan);
		$this->db->delete('kegiatan');
	}
	
	//delete data
	
	//edit data
	function get_by_id($id_kegiatan)
    {
       $this->db->select('a.id_kegiatan,b.nama_donatur,b.telp_donatur,b.alamat_donatur,b.foto_donatur,c.nama_panti_asuhan,c.telp_panti_asuhan,c.alamat_panti_asuhan,c.foto_panti_asuhan,a.nama_kegiatan,a.tanggal_kegiatan,a.jam_kegiatan,a.deskripsi_kegiatan,a.status_kegiatan');
		$this->db->from('kegiatan a');
		$this->db->where('a.id_kegiatan',$id_kegiatan);
		
		$this->db->join('donatur b','a.id_donatur=b.id_donatur');
		$this->db->join('panti_asuhan c','a.id_panti_asuhan=c.id_panti_asuhan');
		//$this->db->order_by('a.status_kegiatan','Menunggu');
		$data = $this->db->get('')->row();
		return $data;
    }
	
	
	function update($id_kegiatan, $data)
    {
        $this->db->where($this->id_kegiatan, $id_kegiatan);
        $this->db->update($this->table, $data);
    }
	
	function updateKegiatan($data)
	{
		$this->db->where('id_kegiatan', $data['id_kegiatan']);
		$this->db->update('kegiatan',$data);
	}
	
	public function get_by_id_edit($id_kegiatan)
	{
		$this->db->from($this->table);
		$this->db->where('id_kegiatan',$id_kegiatan);
		$query = $this->db->get();
		return $query->row();
	}
	
	public function cari($cari)
	{
		$cek=true;
		$this->db->select('a.id_kegiatan,b.nama_donatur,c.nama_panti_asuhan,a.nama_kegiatan,a.tanggal_kegiatan,a.jam_kegiatan,a.deskripsi_kegiatan,a.status_kegiatan');
		$this->db->from('kegiatan a');
		$this->db->join('donatur b','a.id_donatur=b.id_donatur');
		$this->db->join('panti_asuhan c','a.id_panti_asuhan=c.id_panti_asuhan');
		$this->db->like("b.nama_donatur",$cari);
        $this->db->or_like("c.nama_panti_asuhan",$cari);
		$this->db->like("a.tanggal_kegiatan",$cari);
        $this->db->or_like("a.status_kegiatan",$cari);
		$num_rows=$this->db->count_all_results('');
		if($num_rows==0)
		{
		  $cek=false;
		}
		return $cek;
	}
	
	public function hasilcari($cari)
	{
		$this->db->select('a.id_kegiatan,b.nama_donatur,c.nama_panti_asuhan,a.nama_kegiatan,a.tanggal_kegiatan,a.jam_kegiatan,a.deskripsi_kegiatan,a.status_kegiatan');
		$this->db->from('kegiatan a');
		$this->db->join('donatur b','a.id_donatur=b.id_donatur');
		$this->db->join('panti_asuhan c','a.id_panti_asuhan=c.id_panti_asuhan');
		$this->db->like("b.nama_donatur",$cari);
        $this->db->or_like("c.nama_panti_asuhan",$cari);
		$this->db->or_like("a.tanggal_kegiatan",$cari);
        $this->db->or_like("a.status_kegiatan",$cari);
		
		$query = $this->db->get('');

		return $query->result();
	}
	
}

/* End of file Admin_Admin_Model.php */
/* Location: ./application/models/Admin_Admin_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-11 08:36:41 */
/* http://harviacode.com */
